version: '2.1'

services:
  video_web:
    build: .
    container_name: video_web
    ports:
      - "5000:5000"
    restart: always
    volumes: # Mounts the current directory to the container so that changes are reflected
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3